### ISSUE TITLE
Update for ungoogled chromium

### ISSUE THREAD

**Issue by ChaosNicro** [Jonatas-Goncalves/MaxxedSUSE#15]
Heya,
Since going from Leap to Slowroll, I've been using the TW repo and really enjoying the variety in it. It allowed me to condense multiple more specialized OBS repos.

Next to Firefox, I'm also using ungoogled chromium for browsing, which I pulled from a local Nix install. With the more updated repos of Slowroll, UGC is now the only package I couldn't switch off of Nix. Would it be possible to maintain an up to date version in MaxxedSUSE? Was the one that is included now, build from source or pulled from the officially maintained Fedora repos? I don't want to make you any more work, so don't feel pressured to build it on demand,

Thank you.

**Comment by Jonatas-Goncalves** [comment]
First of all, I would like to thank you for choosing to use MaxxedSUSE, and I hope the repository helps you. I also apologize for the delay.

I have updated the current package to version 130.0.6723.58-1, and I will try to keep it updated more frequently.

I have renamed it to ungoogled-chromium-portable so that I can maintain two packages. The other package will be a native ungoogled-chromium binary, but it will take a little longer to release due to some packaging errors I am experiencing.

Please test ungoogled-chromium-portable and report back.
Download package at
https://build.opensuse.org/package/show/home:MaxxedSUSE/ungoogled-chromium-portable

or do
 sudo zypper ref && sudo zypper in ungoogled-chromium-portable

**Comment by ChaosNicro** [comment]
After a slow start because it had to redo the caches, it works great. Thanks. It doesn't have to be updated constantly, but having a recent source is nice.

**Comment by Jonatas-Goncalves** [comment]
Closing issue, package updated.

Thank you for using MaxxedSUSE, and if there is any problem, just let us know.
