### ISSUE TITLE
Add Codeweavers' crossover.

### ISSUE THREAD

**Issue by JMarcosHP** [Jonatas-Goncalves/MaxxedSUSE#8]
[https://www.codeweavers.com/crossover/download-now?distro=rpm](https://www.codeweavers.com/crossover/download-now?distro=rpm)

**Comment by Jonatas-Goncalves** [comment]
This package is the trial?

**Comment by JMarcosHP** [comment]
> This package is the trial?

Yes, sir.

**Comment by Jonatas-Goncalves** [comment]
I created the crossover-trial package and added it to the repository.

I'm trying to compile the llvm compiler from codeweavers, if I can I'll create a FOSS crossover package, but I'm having trouble finding all the dependencies because they don't support the FOSS version and there is little documentation.
If and when I can, I will create a package for FOSS version.

**Comment by Jonatas-Goncalves** [comment]
It took a lot of work but I managed to prepare the crossover-trial package but it is now available and working.

I'm trying to build the llvm compiler from codeweavers needed to build crossover FOSS, when and if I can, I'll create a package for the FOSS version, I remember that a while ago I compiled it, but a lot has changed and there is no documentation and support, I have to discover the dependencies by force.

Please test it and tell me if it worked

![image](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/34562990/061becdf-3619-4612-ab3e-37fd31cd25f1)


![image](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/34562990/a2887c57-96d7-49f3-9d6a-e7f8413c8a5b)

**Comment by JMarcosHP** [comment]
It's working well, thanks.

**Comment by Jonatas-Goncalves** [comment]
Closing issue once it has been completed.
