### ISSUE TITLE
vmware-player-updater has gcc10 missing dependency.

### ISSUE THREAD

**Issue by JMarcosHP** [Jonatas-Goncalves/MaxxedSUSE#9]

**Comment by Jonatas-Goncalves** [comment]
- Change path of package to /usr/share to fix build erros
- Add missing dependencies
- add --deferred-gtk parameter to install silent

Package now works correclty

**Comment by JMarcosHP** [comment]
Installation is successfull but there is no vmware commandline or .desktop launchers.
![Captura de pantalla_20240513_160243](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/58377032/47b34896-7882-4023-96d9-47c5e78abf18)

**Comment by Jonatas-Goncalves** [comment]
I'll investigate

**Comment by Jonatas-Goncalves** [comment]
I tested it here on my desktop and on a fresh VM installing via zypper directly from the repository in the current package and the cli commands are available.

![image](https://github.com/Jonatas-Goncalves/MaxxedSUSE/assets/34562990/5bda73bf-1222-41cb-958a-130e706c3f04)

**Comment by Jonatas-Goncalves** [comment]
about the .desktop launcher there really is an issue in the spec and in the source that I will fix and send an update.

**Comment by Jonatas-Goncalves** [comment]
The package dont efective install Vmware Player, because has an error during installaion script.
Installation script bundle from VMWARE has a problem that search System service scripts directory only in /etc/init.d, and there is no way to pass this value to be filled in during silent install.
I tried extracting the bundle, editing the paths and repackaging it several times, but it didn't work at all, and i used a workaround for the user to execute and add the value during installation adding vmware-player-update.sh that insert an alias to execute /usr/share/.vmware-player-update, that will invoke with --deffered-gtk option and let user insert /etc/systemd/system

Now package install correclty

i found other error in some kernel modules that need be installed: vmmon and vmnet
i add a package vmware-host-modules, but only vmnet is being added, im trying to fix this, but modules can be added from source for now.

Sorry for the delay, I'm finishing other things.

**Comment by Jonatas-Goncalves** [comment]
Closing the issue once the package dependency problem has been resolved and is installing normally.
